Repository mogua-station/FE, pull requests merged in 2025-02, with the labels that each got.

#165 feat(#159): 공통 컴포넌트 테스트 코드 작성 ( modal, popover, dropdown )
  src/tests/dropdown.test.tsx
  src/tests/modals/__snapshots__/modalController.test.tsx.snap
  src/tests/modals/modalController.test.tsx
  src/tests/popover.test.tsx
Labels: 💬 Review Requested

#168 Fix(#167): navBar 경로 수정
  src/components/common/nav-bar/NavBar.tsx
Labels: 🐞 Bug

#147 Feat(#62): 리뷰 작성 페이지
  src/app/user/create_review/page.tsx
  src/assets/images/icons/character_1.svg
  src/assets/images/icons/character_2.svg
  src/assets/images/icons/character_3.svg
  src/assets/images/icons/filled_delete.svg
  src/components/common/buttons/SolidButton.tsx
  src/components/common/card/Card.tsx
  src/components/create-reaview/BackButton.tsx
  src/components/create-reaview/CreateReviewCancelModal.tsx
  src/components/create-reaview/CreateReviewForm.tsx
  src/components/create-reaview/RatingInput.tsx
  src/components/create-reaview/ReviewGreeting.tsx
  src/components/create-reaview/ReviewImageInput.tsx
  src/hooks/review/useReviewMutation.ts
  src/lib/review/reviewApi.ts
Labels: 🛠️ Feature

#170 Feat(#164): 모임 생성/수정 시 임시 저장 기능 추가
  src/components/create/inputs/MeetingDateInput.tsx
  src/components/create/inputs/RecruitmentDateInput.tsx
  src/components/create/modals/ResultInfoModal.tsx
  src/hooks/forms/useLocalStorageForm.ts
  src/hooks/forms/useMeetupForm.tsx
  src/hooks/forms/useMeetupPermissions.tsx
  src/utils/meetupHelpers.ts
Labels: 🛠️ Feature, 💬 Review Requested

#173 Refactor(#123): 유저페이지 수정 및 리팩토링
  src/app/user/[id]/page.tsx
  src/components/common/review/ReviewContent.tsx
  src/components/user-page/UserProfile.tsx
  src/hooks/forms/useMeetupForm.tsx
  src/hooks/user/useEditProfile.ts
  src/hooks/user/useProfile.ts
  src/lib/user/getUserProfile.ts
  src/types/review.ts
  src/utils/userContentMapper.ts
  src/utils/userPage.ts
Labels: 🛠️ Feature, ♻️ Refactor

#177 Refactor(#127): 로그인 토큰 저장 함수 제거
  src/hooks/auths/useSignIn.ts
Labels: ♻️ Refactor

#181 Refactor(#123): 유저페이지 테스트 코드 작성 및 에러 처리 개선
  src/app/user/[id]/error.tsx
  src/app/user/[id]/page.tsx
  src/lib/user/getUserProfile.ts
  src/tests/user-page/UserProfile.test.tsx
  src/tests/user-page/error.test.tsx
  src/tests/user/fetcher.test.ts
  src/tests/user/getUserProfile.test.ts
Labels: 🛠️ Feature, ♻️ Refactor

#184 Refactor(#127): 로그아웃 훅 토큰 삭제 로직 제거
  src/hooks/auths/useSignOut.ts
Labels: ♻️ Refactor, 💬 Review Requested

#183 Feat(#182): 공통 버튼 컴포넌트 테스트 코드 작성
  src/tests/buttons/ETCButton.test.tsx
  src/tests/buttons/IconButton.test.tsx
  src/tests/buttons/OutlineButton.test.tsx
  src/tests/buttons/SolidButton.test.tsx
Labels: 🛠️ Feature

#187 Feat(#153): 모임 상세 알림 추가 및 댓글 기능 수정
  package-lock.json
  package.json
  src/app/study/[id]/page.tsx
  src/app/tutoring/[id]/page.tsx
  src/assets/images/icons/join-check.svg
  src/components/meet-detail/MeetButtonArea.tsx
  src/components/meet-detail/MeetDetail.tsx
  src/components/meet-detail/MeetDetailReview.tsx
  src/components/meet-detail/ShareMeetUpButton.tsx
  src/components/toast/JoinToast.tsx
  src/components/wishlist/WishlistContent.tsx
  src/data/mockList.ts
  src/hooks/useChangeWishlist.ts
  src/hooks/useLoginSetWishlist.ts
  src/lib/meetDetail/meetDetailApi.ts
  src/styles/globals.css
  src/types/meetDetail.ts
  src/utils/copyToClipBorad.ts
  tailwind.config.ts
Labels: 🛠️ Feature, ♻️ Refactor, 💬 Review Requested

#186 Style(#185): 배경에 외계인 추가
  src/app/page.tsx
  src/assets/images/icons/blue.svg
  src/assets/images/icons/earth.svg
  src/assets/images/icons/pink.svg
  src/assets/images/icons/planet-color.svg
  src/assets/images/icons/purple.svg
  src/assets/images/icons/spacecraft-sec.svg
  src/assets/images/icons/yellow.svg
  src/components/main/BackgroundAlien.tsx
Labels: 💬 Review Requested, 🧑🏻‍🎨 Design

#189 Refactor(#188): 에러 컴포넌트 전역 적용
  src/app/error.tsx
  src/tests/error.test.tsx
Labels: ♻️ Refactor

#180 Feat(#169): 공통 모임, 리뷰 카드 컴포넌트 테스트 코드 작성 및 리팩토링
  jest.config.ts
  src/components/common/card/Card.tsx
  src/components/common/card/CardReview.tsx
  src/components/common/card/CardWishlist.tsx
  src/components/common/review/Review.tsx
  src/tests/card/card-create-review.test.tsx
  src/tests/card/card-wishlist.test.tsx
  src/tests/card/card.test.tsx
  src/tests/review.test.tsx
  src/utils/__svgTransformer__.ts
Labels: 🛠️ Feature, ♻️ Refactor

#194 Refactor(#193): fetcher 함수 리팩토링
  src/app/user/[id]/page.tsx
  src/app/user/create_review/page.tsx
  src/components/create-reaview/CreateReviewForm.tsx
  src/components/user-page/MeetingList.tsx
  src/components/user-page/UserTabs.tsx
  src/hooks/review/useReviewMutation.ts
  src/hooks/useInfiniteMeetings.ts
  src/hooks/user/useEditProfile.ts
  src/hooks/user/useProfile.ts
  src/lib/review/reviewApi.ts
  src/lib/user/fetcher.ts
  src/lib/user/getUserProfile.ts
  src/lib/user/userContent.ts
  src/tests/user/fetcher.test.ts
  src/tests/user/getUserProfile.test.ts
  src/types/user-page/index.ts
  src/utils/userPage.ts
Labels: ♻️ Refactor

#197 Fix(#196): 미들웨어 토큰 포함 로직 수정
  src/app/api/auth/verify/route.ts
  src/middleware.ts
Labels: 🐞 Bug, 💬 Review Requested

#191 Refactor(#158): 모임 찾기 페이지 최적화
  next.config.mjs
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/images/icons/mogua.svg
  src/components/common/Header.tsx
  src/components/common/Popover.tsx
  src/components/common/card/Content.tsx
  src/components/common/modals/Modal.tsx
  src/components/main/FilterControls.tsx
  src/components/main/MainContentEmpty.tsx
  src/components/main/MainContentList.tsx
  src/components/main/MeetupSelectionDropdown.tsx
  src/hooks/meetup/useMeetupQueryParams.ts
  src/lib/main/meetup.api.ts
Labels: ♻️ Refactor, 💬 Review Requested

#200 Refactor(#199): RootLayout의 Header, NavBar 조건부 처리
  src/app/layout.tsx
  src/app/user/[id]/page.tsx
  src/app/user/create_review/page.tsx
  src/app/user/edit_profile/page.tsx
  src/components/common/Header.tsx
  src/components/common/layout/HeaderWrapper.tsx
  src/components/common/layout/NavBarWrapper.tsx
  src/components/user/BackButton.tsx
  src/components/user/CancelModal.tsx
  src/components/user/UserHeader.tsx
  src/store/auth/useUserStore.ts
  src/styles/globals.css
Labels: 🛠️ Feature, ♻️ Refactor

#166 Feat(#161): 리뷰 수정, 삭제 추가(API X)
  src/assets/images/icons/menu-circle.svg
  src/components/common/Dropdown.tsx
  src/components/common/review/Review.tsx
  src/components/common/review/ReviewContent.tsx
  src/types/dropdown.type.ts
  src/types/review.ts
Labels: 🛠️ Feature, 🧑🏻‍🎨 Design

#211 Refactor(#123): 유저페이지 수정
  src/app/user/[id]/page.tsx
  src/components/user/BackButton.tsx
  src/components/user/UserHeader.tsx
Labels: 🛠️ Feature, ♻️ Refactor

#208 Feat(#207): 인증이 필요한 페이지 감싸는 컴포넌트 제작
  src/app/create/[id]/page.tsx
  src/app/create/page.tsx
  src/app/user/[id]/page.tsx
  src/app/user/create_review/page.tsx
  src/app/user/edit_profile/page.tsx
  src/components/auth/AuthWrapper.tsx
Labels: 🛠️ Feature, 💬 Review Requested

#210 Refactor(#127): 로그인 인트로 페이지 개선
  src/app/(auth)/sign-in/page.tsx
Labels: ♻️ Refactor, 💬 Review Requested

#212 Refactor(#202): 모임 찾기 페이지에서 서버 캐싱을 활용하여 데이터를 가져오도록 수정
  src/app/page.tsx
  src/components/create/MeetupFormLeft.tsx
  src/components/main/MainContentList.tsx
  src/hooks/meetup/useMeetupMutations.tsx
  src/lib/actions/meetupRevalidate.ts
  src/lib/main/meetup.api.ts
  src/types/meetup.type.ts
Labels: ♻️ Refactor, 💬 Review Requested

#204 Feat(#190): 모임상세 페이지 최적화
  src/app/study/[id]/page.tsx
  src/app/tutoring/[id]/page.tsx
  src/components/common/card/StatusBadge.tsx
  src/components/common/review/Review.tsx
  src/components/meet-detail/MeetButtonArea.tsx
  src/components/meet-detail/MeetDetail.tsx
  src/components/meet-detail/MeetDetailReview.tsx
  src/components/meet-detail/ShareMeetUpButton.tsx
  src/components/toast/JoinToast.tsx
  src/hooks/auths/InitializeUser.ts
  src/hooks/usePrefetchMeetingReview.ts
  src/lib/meetDetail/meetDetailApi.ts
  src/lib/wishlist/wishlistApi.ts
  src/types/meetDetail.ts
Labels: ♻️ Refactor, 💬 Review Requested

#214 Feat(#176): 카카오 로그인 구현
  next.config.mjs
  src/app/(auth)/sign-in/callback/kakao/page.tsx
  src/app/(auth)/sign-in/page.tsx
  src/components/sign-in/KakaoLoginBtn.tsx
  src/lib/auth/useKakaoLogin.ts
Labels: 🛠️ Feature, 💬 Review Requested

#215 Feat(#172): 리뷰수정 페이지
  src/app/user/edit_review/page.tsx
  src/components/common/layout/HeaderWrapper.tsx
  src/components/common/layout/NavBarWrapper.tsx
  src/components/common/review/Review.tsx
  src/components/common/review/ReviewContent.tsx
  src/components/create-reaview/CreateReviewForm.tsx
  src/components/create-reaview/ReviewImageInput.tsx
  src/components/edit-profile/EditProfileForm.tsx
  src/components/edit-review/EditReviewForm.tsx
  src/components/user/UserHeader.tsx
  src/hooks/review/useReviewModals.ts
  src/hooks/review/useReviewMutation.ts
  src/lib/review/reviewApi.ts
Labels: 🛠️ Feature

#216 Feat(#205): 모임상세 페이지 디자인 수정 반영
  src/components/common/review/Review.tsx
  src/components/meet-detail/MeetButtonArea.tsx
  src/components/meet-detail/MeetDetail.tsx
  src/components/meet-detail/MeetDetailReview.tsx
  src/components/meet-detail/ShareMeetUpButton.tsx
  src/lib/meetDetail/meetDetailApi.ts
Labels: 💬 Review Requested, 🧑🏻‍🎨 Design

#218 Feat(#192): 랜딩페이지 이미지 최적화
  src/app/welcome/page.tsx
Labels: ♻️ Refactor, 💬 Review Requested

#220 Feat(#152): 찜하기 필터링 및 로직개선
  public/icons/empty.svg
  src/app/(auth)/sign-in/basic/page.tsx
  src/app/layout.tsx
  src/components/common/card/Card.tsx
  src/components/common/card/Content.tsx
  src/components/common/review/Review.tsx
  src/components/meet-detail/MeetButtonArea.tsx
  src/components/meet-detail/MeetDetail.tsx
  src/components/meet-detail/ShareMeetUpButton.tsx
  src/components/toast/JoinToast.tsx
  src/components/wishlist/WishlistContent.tsx
  src/hooks/auths/InitializeUser.ts
  src/hooks/useChangeWishlist.tsx
  src/hooks/useLoginSetWishlist.ts
  src/lib/meetDetail/meetDetailApi.ts
  src/lib/wishlist/wishlistApi.ts
  src/types/card.ts
  src/types/meetup.type.ts
Labels: 🛠️ Feature, ♻️ Refactor, 💬 Review Requested

#219 Refactor(#132): 프로필 수정 페이지 종합 개선
  src/app/layout.tsx
  src/app/user/edit_profile/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Header.tsx
  src/components/common/nav-bar/NavBar.tsx
  src/components/edit-profile/ContactBanner.tsx
  src/components/edit-profile/EditProfileForm.tsx
  src/components/user/UserHeader.tsx
  src/hooks/auths/useSignOut.ts
  src/hooks/user/useEditProfile.ts
  src/tests/edit-profile/ContactBanner.test.tsx
  src/types/dropdown.type.ts
Labels: ♻️ Refactor

#226 Feat(#225): 모임 상세 페이지 여백 수정
  src/components/meet-detail/MeetDetail.tsx
Labels: ♻️ Refactor, 💬 Review Requested, 🧑🏻‍🎨 Design

#223 Fix(#222): 이미지 삭제 에러 해결
  src/components/common/inputs/ImageUpload.tsx
Labels: 🐞 Bug, 💬 Review Requested

#233 Bug(#230): 리뷰 관련 이슈 해결
  src/components/common/review/Review.tsx
  src/components/common/review/ReviewContent.tsx
  src/components/create-reaview/CreateReviewForm.tsx
  src/components/edit-review/EditReviewForm.tsx
  src/types/review.ts
  src/types/user-page/index.ts
  src/utils/userContentMapper.ts
  src/utils/userPage.ts
Labels: 🛠️ Feature, 🐞 Bug, ♻️ Refactor

#229 Refactor(#158): 모임 찾기 페이지 이미지 LCP 최적화
  src/app/error.tsx
  src/app/layout.tsx
  src/components/common/card/Card.tsx
  src/components/common/card/Content.tsx
  src/components/main/MainContentList.tsx
Labels: ♻️ Refactor, 💬 Review Requested

#232 Feat(#231): 찜한 모임 페이지 padding값추가
  src/app/wishlist/page.tsx
Labels: 🧑🏻‍🎨 Design

#235 Fix(#234): Modify setUser 함수를 언제나 실행되게 변경
  src/hooks/auths/useSignIn.ts
Labels: 🐞 Bug, 💬 Review Requested

#240 Fix(#239): 리뷰 카드 UI 일관성 개선
  src/components/common/review/ReviewContent.tsx
  src/types/review.ts
  src/types/user-page/index.ts
  src/utils/userContentMapper.ts
Labels: 🐞 Bug, ♻️ Refactor, 🧑🏻‍🎨 Design

#244 Fix(#241): 찜한 모임 필터링 깜빡거림 수정
  README.md
  src/app/wishlist/page.tsx
  src/components/wishlist/WishlistContent.tsx
Labels: ♻️ Refactor, 💬 Review Requested
