Repository mogua-station/FE, pull requests merged in 2025-01, with the labels that each got.

#3 Chore(#2): 프로젝트 초기 설정
  .eslintignore
  .eslintrc.json
  .husky/pre-commit
  .prettierignore
  .prettierrc
  jest.config.ts
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  src/app/layout.tsx
  src/app/page.tsx
  src/app/providers/Providers.tsx
  src/styles/globals.css
  tailwind.config.ts
  tsconfig.json
Labels: 🏗️ Chore

#6 Chore(#4): typography
  .gitmessage.txt
  src/app/fonts/PretendardVariable.woff2
  src/app/layout.tsx
  src/app/page.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 🏗️ Chore

#10 Chore(#9): SVGR 설정
  next.config.mjs
  package-lock.json
  package.json
  src/app/page.tsx
  src/assets/images/icons/kakao.svg
  svgr.d.ts
  tsconfig.json
Labels: 🏗️ Chore

#15 Feat(#8): 드롭다운 컴포넌트 제작
  src/app/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/Popover.tsx
  src/styles/globals.css
Labels: 🛠️ Feature

#16 Feat(#8): 네비게이션 바 구현
  src/app/layout.tsx
  src/assets/images/icons/heart.svg
  src/assets/images/icons/planet.svg
  src/assets/images/icons/user.svg
  src/components/common/nav-bar/NavBar.tsx
  src/components/common/nav-bar/NavMenuItem.tsx
Labels: 🛠️ Feature

#19 Feat(#18): 네비게이션 바 적용을 위한 레이아웃 설정
  src/app/layout.tsx
  src/app/page.tsx
Labels: 🛠️ Feature

#17 Feat(#8): 공용 버튼 컴포넌트 제작
  src/app/page.tsx
  src/components/common/buttons/ETCButton.tsx
  src/components/common/buttons/IconButton.tsx
  src/components/common/buttons/OutlinePrimaryButton.tsx
  src/components/common/buttons/OutlineSecondaryButton.tsx
  src/components/common/buttons/SolidButton.tsx
  src/styles/globals.css
  src/types/button.ts
Labels: 🛠️ Feature

#21 Feat(#8): 캘린더 공통 컴포넌트 제작
  src/app/page.tsx
  src/assets/images/icons/arrow_left.svg
  src/components/common/Calendar.tsx
  src/styles/globals.css
  src/utils/generateCalendar.ts
Labels: 🛠️ Feature

#25 Refactor(#23): 캘린더 컴포넌트 커스텀 훅으로 분리
  src/app/page.tsx
  src/components/common/Calendar.tsx
  src/hooks/useCalendar.ts
  src/styles/globals.css
Labels: ♻️ Refactor

#30 Refector(#28): 네비게이션 바 디자인 변경사항 반영
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/images/icons/bookmark_fill.svg
  src/components/common/nav-bar/NavBar.tsx
  tailwind.config.ts
Labels: 🏗️ Chore, 🧑🏻‍🎨 Design

#33 Docs(#1): 인원 변경에 따른 파일 수정
  .github/pull_request_template.md
  .github/workflows/CI.yml
Labels: 🐞 Bug, 🧑🏻‍🎨 Design

#20 Feat(#8): 공용 카드 컴포넌트 추가
  src/app/page.tsx
  src/assets/images/icons/announcement-megaphone.svg
  src/assets/images/icons/bookmark.svg
  src/assets/images/icons/bookmarkActive.svg
  src/assets/images/icons/fire.svg
  src/assets/images/icons/waving-hand.svg
  src/components/common/card/Card.tsx
  src/components/common/card/Content.tsx
  src/components/common/card/StatusBadge.tsx
  src/styles/globals.css
  src/types/card.ts
Labels: 🛠️ Feature

#32 Refector(#28): 네비게이션 바 태블릿 디자인 수정
  src/components/common/nav-bar/NavBar.tsx
Labels: 🧑🏻‍🎨 Design

#31 Feat(#8): Header 컴포넌트 추가
  public/icons/mogua.svg
  src/app/layout.tsx
  src/assets/images/icons/edit.svg
  src/assets/images/icons/plus-thin.svg
  src/assets/images/icons/search-thin.svg
  src/components/common/Header.tsx
Labels: 🛠️ Feature

#29 Feat(#8): 공통 리뷰 컴포넌트
  public/images/default_user_profile.png
  src/app/page.tsx
  src/assets/images/icons/arrow_down.svg
  src/assets/images/icons/rating.svg
  src/components/common/review/Review.tsx
  src/components/common/review/ReviewContent.tsx
  src/styles/globals.css
  src/types/review.ts
Labels: 🛠️ Feature

#27 Refector(#22): 버튼 공통 컴포넌트 개선
  src/app/page.tsx
  src/components/common/buttons/ETCButton.tsx
  src/components/common/buttons/IconButton.tsx
  src/components/common/buttons/OutlineButton.tsx
  src/components/common/buttons/OutlinePrimaryButton.tsx
  src/components/common/buttons/OutlineSecondaryButton.tsx
  src/components/common/buttons/SolidButton.tsx
  src/styles/globals.css
  src/types/button.ts
Labels: ♻️ Refactor, 🧑🏻‍🎨 Design

#34 Feat(#8): 모달 공통 컴포넌트 추가
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/app/providers/Providers.tsx
  src/assets/images/icons/delete.svg
  src/assets/images/icons/info.svg
  src/assets/images/icons/reset_thin.svg
  src/components/common/Calendar.tsx
  src/components/common/buttons/IconButton.tsx
  src/components/common/modals/CalendarModal.tsx
  src/components/common/modals/CityModal.tsx
  src/components/common/modals/FilterModal.tsx
  src/components/common/modals/Modal.tsx
  src/components/common/modals/StateModal.tsx
  src/hooks/useCalendar.ts
  src/hooks/useModal.tsx
  src/hooks/useSelectedDateRange.ts
  src/types/button.ts
  src/types/overlay.type.ts
  tailwind.config.ts
Labels: 🛠️ Feature

#39 Refactor(#37): 공통 레이아웃 높이 구조 개선
  src/app/layout.tsx
Labels: 🧑🏻‍🎨 Design

#46 Fix(#45): merge 동작 관련 코드 수정
  .github/workflows/CI.yml
Labels: 🐞 Bug

#53 Feat(#52): CI 파일 추가
  .github/workflows/CI_DEVELOP_PR-.yml
  .github/workflows/CI_DEVELOP_PUSH.yml
  .github/workflows/CI_MAIN_PR.yml
Labels: 🛠️ Feature, 📜 Docs

#56 Fix(#54): workflow 자동 머지 이슈 해결
  .github/workflows/CI_DEVELOP_PR-.yml
Labels: 🐞 Bug, 💬 Review Requested

#60 Refactor(#59): TQ Provider 설정 변경
  src/app/providers/Providers.tsx
Labels: ♻️ Refactor, 💬 Review Requested

#64 Feat(#63): Header 컴포넌트 z-index 속성 추가
  src/components/common/Header.tsx
Labels: 🧑🏻‍🎨 Design

#68 Style(#67): mobile, tablet 좌우 padding 추가
  src/app/layout.tsx
Labels: 🧑🏻‍🎨 Design

#42 Feat(#2): 공통 input 컴포넌트 추가
  .eslintrc.json
  .github/workflows/SYNC_TO_DEPLOY_REPOSITORY.yml
  package-lock.json
  package.json
  src/app/(example)/input/page.tsx
  src/app/page.tsx
  src/assets/images/icons/camera.svg
  src/assets/images/icons/visibility_off.svg
  src/assets/images/icons/visibility_on.svg
  src/components/auth/PasswordInput.tsx
  src/components/common/inputs/ImageUpload.tsx
  src/components/common/inputs/MANUAL.md
  src/components/common/inputs/SelectBox.tsx
  src/components/common/inputs/TextInput.tsx
  src/components/common/inputs/VisibilityToggle.tsx
  src/hooks/inputs/auth/useAuthInput.ts
  src/hooks/inputs/images/useIndexedDB.ts
  src/hooks/inputs/images/usePostImage.ts
  src/hooks/inputs/images/useUploadImage.ts
  src/hooks/inputs/style.ts
  src/tests/inputs/ImagePost.test.tsx
  src/tests/inputs/ImageUpload.test.tsx
  src/types/index.d.ts
  tailwind.config.ts
Labels: 🛠️ Feature, 💬 Review Requested

#58 Feat(#57): 모임카드 마감일 표기 수정
  src/components/common/card/Card.tsx
  src/components/common/card/StatusBadge.tsx
  src/types/card.ts
Labels: ♻️ Refactor, 🧑🏻‍🎨 Design

#70 Refactor(#69): 캘린더 컴포넌트 및 훅 분리
  src/app/page.tsx
  src/components/common/calendar/Calendar.tsx
  src/components/common/calendar/CalendarDatesGrid.tsx
  src/components/common/calendar/CalendarDaysOfWeek.tsx
  src/components/common/calendar/CalendarHeader.tsx
  src/components/common/modals/CalendarModal.tsx
  src/constants/calendar.constant.ts
  src/hooks/calendar/useCalendar.ts
  src/hooks/calendar/useCalendarHelpers.ts
  src/hooks/calendar/useSelectedDateRange.ts
  src/hooks/useCalendar.ts
  src/types/date.type.ts
  src/utils/calendarUtils.ts
Labels: ♻️ Refactor, 💬 Review Requested

#71 Feat(#14): 자체 로그인 예시 페이지
  src/app/(auth)/sign-in/basic/page.tsx
  src/components/auth/AuthInputs.tsx
  src/components/auth/PasswordInput.tsx
  src/hooks/auths/useSignIn.ts
Labels: 🛠️ Feature

#73 Feat(#2): 공통 Text Area 추가
  package-lock.json
  package.json
  src/app/(example)/input/page.tsx
  src/components/common/inputs/SelectBox.tsx
  src/components/common/inputs/TextArea.tsx
  src/components/common/inputs/TextInput.tsx
  src/hooks/inputs/style.ts
Labels: 💬 Review Requested, 🧑🏻‍🎨 Design

#84 Feat(#81): 모임카드, 칩 컴포넌트 타입수정
  src/app/study/[id]/page.tsx
  src/app/tutoring/[id]/page.tsx
  src/components/common/card/Card.tsx
  src/components/common/card/Content.tsx
  src/components/common/card/StatusBadge.tsx
  src/components/main/MainContentList.tsx
  src/components/meet-detail/MeetDetail.tsx
  src/data/mockCardData.ts
  src/data/mockList.ts
  src/types/card.ts
Labels: ♻️ Refactor

#76 Fix(#75): indexedDB 초기 objectStore 생성 문제 해결
  src/hooks/inputs/images/useIndexedDB.ts
  src/hooks/inputs/images/useUploadImage.ts
Labels: 🐞 Bug, 💬 Review Requested

#87 Fix(#86): mock 데이터 타입오류 수정
  src/data/mockCardData.ts
Labels: 🐞 Bug

#85 Style(#8): 공통 Text Area CSS 수정
  src/app/(example)/input/page.tsx
  src/components/common/inputs/TextArea.tsx
Labels: 💬 Review Requested, 🧑🏻‍🎨 Design

#83 Feat(#14): 로그인 관련 커스텀 훅 추가
  src/app/(example)/input/page.tsx
  src/app/layout.tsx
  src/hoc/withAuth.tsx
  src/hooks/auths/InitializeUser.ts
  src/hooks/auths/useRedirectIfUnsigned.ts
  src/hooks/auths/useSignIn.ts
  src/hooks/auths/useTokenState.ts
  src/store/auth/useUserStore.ts
Labels: 🛠️ Feature, 💬 Review Requested

#78 Feat(#12): 모임 찾기 페이지 API 연동 및 구현
  src/app/(example)/example/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/images/icons/bell.svg
  src/components/common/skeleton/CardSkeleton.tsx
  src/components/main/FilterControls.tsx
  src/components/main/MainContentList.tsx
  src/components/main/MainNavigation.tsx
  src/components/main/MeetupSelectionDropdown.tsx
  src/components/main/modals/FilterModal.tsx
  src/components/main/modals/LocationModal.tsx
  src/components/main/modals/StateModal.tsx
  src/lib/main/meetup.api.ts
  src/types/meetup.type.ts
Labels: 🛠️ Feature, 💬 Review Requested

#80 Feat(#61): 프로필 수정 페이지
  src/app/layout.tsx
  src/app/user/edit_profile/page.tsx
  src/assets/images/icons/camera.svg
  src/components/auth/AuthInputs.tsx
  src/components/common/CountIndicator.tsx
  src/components/common/inputs/TextArea.tsx
  src/components/common/inputs/TextInput.tsx
  src/components/common/nav-bar/NavBar.tsx
  src/components/edit-profile/AccountActionButtons.tsx
  src/components/edit-profile/ContactBanner.tsx
  src/components/edit-profile/EditProfileForm.tsx
  src/components/edit-profile/ProfileImageInput.tsx
  src/components/edit-profile/Tag.tsx
  src/components/edit-profile/TagInput.tsx
  src/constants/alerts.ts
  src/hooks/useSimpleImageUpload.ts
  src/hooks/user/useEditProfile.ts
  src/hooks/user/useProfile.ts
  src/lib/user/clientFetch.ts
  tailwind.config.ts
Labels: 🛠️ Feature

#92 Fix(#91): useTokenState 클라이언트 사이드에서만 작동하도록 변경
  src/hooks/auths/useTokenState.ts
Labels: 🐞 Bug, 💬 Review Requested

#88 Style(#14): 회원가입 페이지 CSS
  src/app/(auth)/sign-up/page.tsx
  src/app/(auth)/sign-up/success/page.tsx
  src/components/auth/AuthInputs.tsx
Labels: 💬 Review Requested, 🧑🏻‍🎨 Design

#82 Feat(#77): 모임 생성 페이지 제작
  src/app/create/page.tsx
  src/assets/images/icons/location.svg
  src/assets/images/icons/minus.svg
  src/assets/images/icons/plus.svg
  src/components/common/Header.tsx
  src/components/common/inputs/ImageUpload.tsx
  src/components/common/inputs/SelectBox.tsx
  src/components/common/modals/Modal.tsx
  src/components/create/CloseButton.tsx
  src/components/create/CreateForm.tsx
  src/components/create/FormSectionLeft.tsx
  src/components/create/FormSectionRight.tsx
  src/components/create/inputs/DateInputSection.tsx
  src/components/create/inputs/MeetingDateInput.tsx
  src/components/create/inputs/MeetingTypeSection.tsx
  src/components/create/inputs/ParticipantsInput.tsx
  src/components/create/inputs/RecruitmentDateInput.tsx
  src/components/create/modals/MeetingDateModal.tsx
  src/components/create/modals/RecruitmentDateModals.tsx
  src/components/create/modals/ResultInfoModal.tsx
  src/hooks/useModal.tsx
  src/lib/main/meetup.api.ts
  src/styles/globals.css
  src/types/meetup.type.ts
  src/types/overlay.type.ts
Labels: 🛠️ Feature, 💬 Review Requested

#98 Feat(#96)네비게이션 바 유저정보 연결
  src/app/layout.tsx
  src/components/common/nav-bar/NavBar.tsx
Labels: 🛠️ Feature

#95 Style(#14): 회원가입 페이지 CSS 추가
  src/app/(auth)/sign-up/page.tsx
Labels: 💬 Review Requested, 🧑🏻‍🎨 Design

#99 Fix(#97): 모달을 열었을 때 배경이 늘어나는 문제 해결
  src/components/common/modals/Modal.tsx
Labels: 🐞 Bug, 💬 Review Requested

#103 Fix(#102): Sync 자동화 로직 수정
  .github/workflows/SYNC_TO_DEPLOY_REPOSITORY.yml
Labels: 🐞 Bug, 💬 Review Requested

#106 Feat(#13): 유저페이지 로그인 토큰 적용
  src/app/user/[id]/page.tsx
  src/components/user-page/MeetingList.tsx
  src/components/user-page/UserTabs.tsx
  src/hooks/useInfiniteMeetings.ts
  src/types/user-page/index.ts
  src/utils/userContentMapper.ts
  src/utils/userPage.ts
Labels: ♻️ Refactor

#109 Feat(#11): 찜하기 페이지 기능 구현
  src/app/(auth)/sign-in/basic/page.tsx
  src/app/wishlist/page.tsx
  src/components/common/card/Card.tsx
  src/components/common/card/CardSkeleton.tsx
  src/components/common/card/Content.tsx
  src/components/common/card/StatusBadge.tsx
  src/components/meet-detail/MeetButtonArea.tsx
  src/components/wishlist/WishlistContent.tsx
  src/hooks/auths/InitializeUser.ts
  src/hooks/useInterSectionObserve.ts
  src/hooks/useToggleWishlist.ts
  src/lib/wishlist/wishlistApi.ts
  src/store/wishlist/useUserWishlist.ts
  src/types/card.ts
Labels: 🛠️ Feature

#110 Feat(#13): 유저페이지에 모임생성 페이지 이동 연결
  src/components/common/review/ReviewContent.tsx
  src/components/user-page/EmptyState.tsx
  src/components/user-page/MeetingList.tsx
  src/types/user-page/index.ts
Labels: 🛠️ Feature

#112 Feat(#111): 프로필 수정 페이지 경로이동 및 로그아웃 연결
  src/components/common/Header.tsx
  src/components/edit-profile/AccountActionButtons.tsx
Labels: 🛠️ Feature

#108 Fix(#107): 모임 생성 시 쿠키에서 토큰을 못 받아오는 문제 해결
  src/components/create/CreateForm.tsx
  src/lib/main/meetup.api.ts
  src/utils/cookie.ts
Labels: 🐞 Bug, 💬 Review Requested

#119 Fix(#118): 유저페이지의 목록이 갑자기 안 보이는 문제
  src/components/user-page/MeetingList.tsx
  src/constants/pagination.ts
  src/hooks/useInfiniteMeetings.ts
  src/lib/user/userContent.ts
  src/types/user-page/index.ts
  src/utils/userContentMapper.ts
  src/utils/userPage.ts
Labels: 🐞 Bug

#113 Feat(#66): 모임 상세 페이지 API 연동
  src/app/study/[id]/page.tsx
  src/app/tutoring/[id]/page.tsx
  src/components/common/card/Card.tsx
  src/components/common/card/StatusBadge.tsx
  src/components/meet-detail/MeetButtonArea.tsx
  src/components/meet-detail/MeetDetail.tsx
  src/components/meet-detail/MeetDetailReview.tsx
  src/components/meet-detail/ShareMeetUpButton.tsx
  src/data/mockList.ts
  src/hooks/usePrefetchMeetingReview.ts
  src/lib/meetDetail/meetDetailApi.ts
  src/types/meetDetail.ts
  src/types/review.ts
  src/utils/copyToClipBorad.ts
Labels: 🛠️ Feature, ♻️ Refactor

#121 Fix(#120): 모임카드 디자인 이슈 수정
  src/components/common/card/Card.tsx
Labels: 🐞 Bug, 💬 Review Requested

#128 Style(#/127): 회원가입 완료 페이지 애니메이션 추가
  package-lock.json
  package.json
  src/app/(auth)/sign-up/success/page.tsx
Labels: 🧑🏻‍🎨 Design

#124 Refactor(#122): 모임 찾기 시 모임이 없다면 메시지 표시
  src/app/page.tsx
  src/components/main/MainContentList.tsx
  src/components/main/modals/LocationModal.tsx
  src/lib/main/meetup.api.ts
  src/utils/meetup.queryKey.ts
Labels: ♻️ Refactor, 💬 Review Requested, 🧑🏻‍🎨 Design

#133 Fix(#131): 모임상세 API 환경변수명 수정
  src/components/meet-detail/MeetButtonArea.tsx
  src/lib/meetDetail/meetDetailApi.ts
Labels: 🐞 Bug

#135 Fix(#134): 모임 생성이 되지 않는 문제 해결
  src/components/create/CreateForm.tsx
  src/components/create/FormSectionLeft.tsx
  src/lib/main/meetup.api.ts
Labels: 🐞 Bug, 💬 Review Requested

#138 Refactor(#137): 헤더 마이페이지 라우팅 추가
  src/components/common/Header.tsx
Labels: ♻️ Refactor

#136 Refactor(#130): 모달을 util로 관리하도록 수정
  src/app/(example)/example/page.tsx
  src/components/common/modals/Modal.tsx
  src/components/create/CreateForm.tsx
  src/components/create/inputs/MeetingDateInput.tsx
  src/components/create/inputs/RecruitmentDateInput.tsx
  src/components/create/modals/MeetingDateModal.tsx
  src/components/create/modals/RecruitmentDateModals.tsx
  src/components/create/modals/ResultInfoModal.tsx
  src/components/main/MainNavigation.tsx
  src/components/main/modals/FilterModal.tsx
  src/hooks/useModal.tsx
  src/types/overlay.type.ts
  src/utils/modalController.tsx
Labels: ♻️ Refactor, 💬 Review Requested

#140 Fix(#139): 쿠키가 저장되지 않는 이슈
  src/hooks/auths/useSignIn.ts
Labels: 🐞 Bug

#141 Refactor(#123): 유저페이지 데이터 요청 관련 리팩토링
  src/app/user/[id]/error.tsx
  src/app/user/[id]/page.tsx
  src/components/common/skeleton/SkeletonList.tsx
  src/components/user-page/MeetingList.tsx
  src/components/user-page/ReviewTabs.tsx
  src/components/user-page/StudyTypeFilter.tsx
  src/components/user-page/TabList.tsx
  src/components/user-page/UserProfile.tsx
  src/hooks/user/useProfile.ts
  src/lib/user/clientFetch.ts
  src/lib/user/fetcher.ts
  src/lib/user/getUserProfile.ts
  src/lib/user/userContent.ts
  src/types/user-page/index.ts
  src/utils/userPage.ts
Labels: ♻️ Refactor

#145 Fix(#144): workflow_run 정확한 파일 이름으로 변경
  .github/workflows/SYNC_TO_DEPLOY_REPOSITORY.yml
Labels: 🐞 Bug, 💬 Review Requested

#146 Fix(#144): 파일명이 아닌 workflow name으로 롤백
  .github/workflows/SYNC_TO_DEPLOY_REPOSITORY.yml
Labels: 🐞 Bug, 💬 Review Requested

#149 Fix(#148): 회원가입 에러 로직 수정
  src/hooks/auths/useSignUp.ts
Labels: 🐞 Bug, 💬 Review Requested

#151 Refactor(#126): 찜하기 기능 리팩토링
  src/app/(auth)/sign-in/basic/page.tsx
  src/app/(auth)/sign-in/page.tsx
  src/app/wishlist/page.tsx
  src/components/common/card/Card.tsx
  src/components/common/card/StatusBadge.tsx
  src/components/meet-detail/MeetButtonArea.tsx
  src/components/wishlist/WishlistContent.tsx
  src/hooks/auths/InitializeUser.ts
  src/hooks/useChangeWishlist.ts
  src/hooks/useLoginSetWishlist.ts
  src/hooks/usePrefetchMeetingReview.ts
  src/hooks/useToggleWishlist.ts
  src/lib/wishlist/wishlistApi.ts
  src/store/wishlist/useUserWishlist.ts
  src/types/card.ts
Labels: ♻️ Refactor

#154 Feat(#125): 모임 생성 시 과외 모임 타입 추가 및 모임 수정 기능 추가
  next.config.mjs
  src/app/create/[id]/page.tsx
  src/components/common/inputs/ImageUpload.tsx
  src/components/create/CreateForm.tsx
  src/components/create/FormSectionLeft.tsx
  src/components/create/FormSectionRight.tsx
  src/components/create/MeetupFormLeft.tsx
  src/components/create/MeetupFormRight.tsx
  src/components/create/inputs/DateInputSection.tsx
  src/components/create/inputs/FormatTypeSelection.tsx
  src/components/create/inputs/MeetingDateInput.tsx
  src/components/create/inputs/MeetingTypeSelection.tsx
  src/components/create/inputs/ParticipantsInput.tsx
  src/components/create/inputs/RecruitmentDateInput.tsx
  src/components/create/modals/ResultInfoModal.tsx
  src/hooks/forms/useMeetupForm.tsx
  src/hooks/inputs/images/useIndexedDB.ts
  src/hooks/inputs/images/useUploadImage.ts
  src/hooks/meetup/useMeetupMutations.tsx
  src/lib/main/meetup.api.ts
  src/styles/globals.css
  src/types/meetup.type.ts
  src/utils/compareDates.ts
  src/utils/meetupDefault.ts
Labels: 🛠️ Feature

#155 Style(#127): 로그인 요청 시 Spinner 리액션 추가
  package-lock.json
  package.json
  src/app/(auth)/sign-in/basic/page.tsx
Labels: 💬 Review Requested, 🧑🏻‍🎨 Design

#156 Style(#127): 회원가입 요청 시 Spinner 이벤트 추가
  src/app/(auth)/sign-up/page.tsx
Labels: 💬 Review Requested, 🧑🏻‍🎨 Design

#157 Refactor(#127): useUserStore 로직 개선
  src/store/auth/useUserStore.ts
Labels: ♻️ Refactor, 💬 Review Requested

#163 Feat(#162): 페이지 이동시 idb에 저장된 이미지 삭제 추가
  src/app/layout.tsx
  src/hooks/inputs/images/useLeavePage.ts
Labels: 🛠️ Feature, 💬 Review Requested

#160 Refactor(#158): 모임 찾기 페이지 리팩토링
  src/app/page.tsx
  src/app/wishlist/page.tsx
  src/components/common/Dropdown.tsx
  src/components/common/card/Content.tsx
  src/components/main/MainContentList.tsx
  src/components/main/MainNavigation.tsx
  src/hooks/meetup/useMeetupList.ts
  src/hooks/meetup/useMeetupQueryParams.ts
  src/hooks/meetup/useMeetupUpdateQuery.ts
  src/hooks/useInfiniteScroll.ts
Labels: ♻️ Refactor, 💬 Review Requested
